### ISSUE TITLE
Search result does not move cursor, only selection

### ISSUE THREAD

**Issue by beowulfof** [wunderfeyd/tippse#10]
After a search, moving with left/right sets the cursor on the line of the search result, whereas moving with up/down sets the cursor from last position before the search.

**Comment by wunderfeyd** [comment]
Thank you for your bug report. Yes, that's correct. The cursor position resets to the previous value in this case. I'll update this the next commits.

**Comment by wunderfeyd** [comment]
Cursor position is now updated. Please use the latest commit. Does it work for you?

**Comment by wunderfeyd** [comment]
This issue is closed. If you think the function is not as you expected reopen the issue please.
