### ISSUE TITLE
sometimes search won't set cursor again

### ISSUE THREAD

**Issue by beowulfof** [wunderfeyd/tippse#16]
Under some circumstances, the cursor is not visible after a search. Seems to correlate with the search-result line beeing the last visible line.

**Comment by wunderfeyd** [comment]
Thanks for creating a issue for this one. But I can't reproduce what you have experienced. The content for the cursor position is scrolled into the view always. The cursor is hidden only if a selection is active.

To continue here, we need steps to reproduce the effect. Your terminal emulation application and your application settings could also be interesting also. Do you have more details here?

**Comment by beowulfof** [comment]
Update. To reproce:

1. search with F3 for a string further down in the document
2. switch via F5 to compile window
3. use ctrl+o to jump to code line in previous search document
4. cursor is out of view

**Comment by wunderfeyd** [comment]
Thanks that helped a lot. Selection is invalidated after any goto command now. We have to check in future if other commands should behave the same way.
