### ISSUE TITLE
tab-length setting?

### ISSUE THREAD

**Issue by beowulfof** [wunderfeyd/tippse#19]
It would be nice to have a tab setting, defining the tabulator length. 

tippse is currently selecting Space*1 for cpp documents which is really annoying, since it matches the brackets based on it. It would be very nice, if I can define a useful (for my cases) fallback ideally based on file type.

**Comment by wunderfeyd** [comment]
Thank you for your enhancement request. Tippse is auto detecting the tab/space interval and chooses the best fitting one. During auto detection the smallest indentation is used to set the space multiplicator. That means your document has an odd space count indentation somewhere.

Nevertheless you are right, one should have the opportunity to set the tab width, tab style and default line ending in the config file. I'm going to add this as an override for all document types and as an override for each document type.

Also I will change the tab width threshold during auto detection to allow a few wrong indented lines.

**Comment by wunderfeyd** [comment]
`newline` (`auto`, `cr`, `lf`, `crlf`), `tabstop` (`auto`, `space`, `tab`)  and `tabstop_width` (`0` = automatic) overrides in main config section and individual overrides for each file type.

The threshold has not been implemented. It was too difficult to find a balanced and good way yet.

Thanks for your enhancement request. Let me know if something is wrong or still missing.

**Comment by wunderfeyd** [comment]
fe31983d25acafa8390660f2f002199f1e795e93
