### ISSUE TITLE
Request: open file state save

### ISSUE THREAD

**Issue by beowulfof** [wunderfeyd/tippse#20]
It would be very useful if tippse could save the currently opened files in a status when closed, that are reopened upon next start.

**Comment by wunderfeyd** [comment]
Thank you for the enhancement request. Yes, it's a good idea. What would you prefer:
* All document file paths should be saved to the profile folder
* All document file paths should be written to the next config folder (for example your project settings)
* Project specific file paths should be stored next to config folder each (nearest paths)

Or do you need another behavior?

**Comment by beowulfof** [comment]
Since tippse does not know about a project to date, I think the the third option looks best to me, but it would clutter the filesystem with junk. So maybe use the profile folder ~/.tippse to save, but cluster the pathes by the path of the nearest config file?

Just a thought:
{
  state: {
  configpath: /prj/a/src/.tippse,
  filelist: {
    a/b/c,
    a/b/d,
    a/b/f/e,
  },
  configpath: /prj/b/src/.tippse,
  filelist: {
    a/b/c,
    a/b/d,
    a/b/f/e,
  },   
}

**Comment by wunderfeyd** [comment]
Yes nice idea. But it should tag project files/config files with some unique identifier... this could help when the project files (including the `.tippse` document) have been moved.

**Comment by beowulfof** [comment]
So maybe introduce a part of the config file with project definitions?

**Comment by wunderfeyd** [comment]
Yes, when time has come we can try a few alternatives regarding this point. But it sounds good from the perspective of the current project status.

**Comment by wunderfeyd** [comment]
After some time of discussing and thinking around this issue, the feature was added in the following way:
A command line parameter `--state|-s statefile` was introduced. It loads the state on startup and saves the state on exit. Documents, splitter and views are saved/restored.

I hope it is good enough for the first step. If something additional is needed, open a new issue.
