### ISSUE TITLE
freeze: by using [del] in filter dialog after saveas

### ISSUE THREAD

**Issue by beowulfof** [wunderfeyd/tippse#23]
steps to reproduce:
1. open a file
2. select saveas command
3. press [POS1] to get to first character in filterdialog
4. add some characters
5. press [DEL]

tippse freezes by computing at high load

**Comment by wunderfeyd** [comment]
Thanks for your bug report. I'll dig into it right now.

**Comment by wunderfeyd** [comment]
The filter field was filled with a low level method. But the bookmark array was not adapted accordingly. Switched to a more correct high level method which is handling everything on the fly.

Please update to the latest version. Thanks for the bug report and the nice steps to reproduce.
