### ISSUE TITLE
linker error on ubuntu

### ISSUE THREAD

**Issue by beowulfof** [wunderfeyd/tippse#24]
/opt/Source/tippse$ ./make.sh
/tmp/cc6yQEXC.ltrans1.ltrans.o: In Funktion »document_text_transform.constprop.13«:
<artificial>:(.text.unlikely+0x947): Warnung: undefinierter Verweis auf »encoding_cache_find_length«
collect2: error: ld returned 1 exit status

error occurs since b01747ba5725f24e267e97bc564f57cfac030ede

**Comment by wunderfeyd** [comment]
Thank you very much for reporting this issue.

It seems some functions are already thrown away during the compilers LTO pass if already inlined. Changed the inline to a "force inline". This also undos the hack from Issue #13.

Please update to the latest version. If you have trouble with this again, reopen this ticket please.
