### ISSUE TITLE
undeclared identifier 'PTHREAD_MUTEX_ADAPTIVE_NP' on macOS

### ISSUE THREAD

**Issue by heptal** [wunderfeyd/tippse#26]
> $ **`make debug`**

CC src/clipboard.c
CC src/tools/convert.c
*src/tools/convert.c:80:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
1 warning generated.*
LD tmp/tools/convert
CO src/config.default.txt
CC src/config.c
*src/config.c:317:51: warning: expression does not compute the number of elements in this array; element type is 'size_t'
      (aka 'unsigned long'), not 'int' [-Wsizeof-array-div]
            if (brackets<sizeof(bracket_positions)/sizeof(int)) {
                                ~~~~~~~~~~~~~~~~~ ^
src/config.c:293:12: note: array 'bracket_positions' declared here
    size_t bracket_positions[1024];
           ^
src/config.c:317:51: note: place parentheses around the 'sizeof(int)' expression to silence this warning
            if (brackets<sizeof(bracket_positions)/sizeof(int)) {
                                                  ^
1 warning generated.*
CC src/document.c
...
...
CC src/library/misc.c
CC src/library/mutex.c
**src/library/mutex.c:10:48: error: use of undeclared identifier 'PTHREAD_MUTEX_ADAPTIVE_NP'
  pthread_mutexattr_settype(&mutex->attribute, PTHREAD_MUTEX_ADAPTIVE_NP);
                                               ^
_1 error generated._
make: \*\*\* [tmp/src/library/mutex.o] Error 1**

**Comment by wunderfeyd** [comment]
Thank you very much for your build problem report. Can you please retry with latest commit (ebe1e5bcd6566410033aae752945f303d37b5f08)? I also added a automatic workflow for MacOS now.

I had no real MacOS on my work place lately to test the UI, if you experience other issues let me know (in a separate github issue).

**Comment by markseuffert** [comment]
I can confirm it works on my Mac, I could build it with/without debug.

**Comment by wunderfeyd** [comment]
Thank you @markseu.
